Minimal documentation
contributte/apitte-console pull request #3
Opened 2018-01-16 16:45 UTC by kralmichal

Ref. https://github.com/apitte/console/issues/2

2018-01-16 16:57 UTC, f3l1x commented on .docs/README.md
> +		tags: [kdyby.console.command]
Well, ... Ehm.

2018-01-16 17:09 UTC, f3l1x requested changes

2018-01-16 17:09 UTC, f3l1x commented on .docs/README.md
> +`php bin/console route:dump`
It should be prefixed with the vendor name such as `apitte:route:dump` to prevent duplication.

2018-01-19 14:45 UTC, merged

2018-01-19 14:45 UTC, f3l1x commented
Thank you.

2018-01-19 14:47 UTC, kralmichal commented
Thanks for merge.